baseURL = "https://kiberdruzhinnik.ru/"
languageCode = "ru"
defaultContentLanguage = "ru"

title = "Кибердружинник"
copyright = "2023 / Hugo / Lynx"

enableEmoji = false
disableKinds = ["taxonomy", "term"]

[author]
  # name = "Константин Романов"
  headline = "Прохождения CTF-машин."
  image = "img/author.png"  # path relative to static directory

  links = [
    { telegram =  { href = "https://t.me/kiberdruzhinnik", text = "Telegram"} },
    { teletype = { href = "https://teletype.kiberdruzhinnik.ru/", text="Teletype" } },
    { hashnode = { href = "https://hashnode.kiberdruzhinnik.ru", text="Hashnode" } },
    { dzen = { href = "https://dzen.ru/kiberdruzhinnik", text="Дзен" } },
    { github = { href = "https://github.com/kotasher", text="Github" } },
    # { linkedin = { href = "https://linkedin.com/in/kotasha-romanov", text = "Linkedin" } },
    # { email = "mailto:hello@your_domain.com" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { youtube = "https://youtube.com/username" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
